server:
  port: 8083

spring:
  datasource:
    url: jdbc:postgresql://keycloak:5435/kinetics_database
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update
    database: postgresql
    show-sql: true
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://keycloak:8080/realms/kinetics-app-realm
          jwk-set-uri: http://keycloak:8080/realms/kinetics-app-realm/protocol/openid-connect/certs
      client:
        provider:
          keycloak:
            issuer-uri: http://keycloak:8080/realms/kinetics-app-realm
            user-name-attribute: preferred_username
        registration:
          keycloak:
            client-id: kinetics-app-client
            client-secret: vPCsg4rrpS2QtavO3lob0MsyxBldEgoz
            scope: openid, profile, email  # Add needed scopes
#            redirect-uri: "http://localhost:8083/login/oauth2/code/keycloak"
#            client-authentication-method: client_secret_basic

logging:
  level:
    org.springframework.security: TRACE

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html